server:
  port: 8080

spring:
  application:
    name: test-web
  plugin:
    active: disable

logging:
  file:
    max-size: 200MB
  pattern:
    console: '[%X{flowno}] %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
    file: ${logging.pattern.console}
  level:
    'com.test': 'DEBUG'

  ### 放开Actuator Web REST端点 ###
management:
  endpoints:
    web:
      base-path: /actuator  # 访问根路径
      exposure:
        include: "*"
    enabled-by-default: true
