server:
  port: 8100

my-security:
  whitelist:
    - /test
    - /login
    - /error
    - /sec/formLogin
    - /sec/jsonLogin
    - /sec/cookieLogin

  loginUrl: /login
  jwtProperties:
    # jwt sign算法
    algorithm: hs512
    # jwt secret
    secret: http-security-secret-modify-mehttp-security-secret-modify-mehttp-security-secret-modify-mehttp-security-secret-modify-mehttp-security-secret-modify-mehttp-security-secret-modify-mehttp-security-secret-modify-mehttp-security-secret-modify-mehttp-security-secret-modify-mehttp-security-secret-modify-me
    # jwt 有效时间
    expiration-in-second: 1209600